version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn && yarn cache clean --force
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - build/**/*
    - node_modules/**/*