# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:13
    container_name: centro-medico
    restart: on-failure
    environment:
      POSTGRES_DB: cmu
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1986
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: "host"
# cambiar   postgresql 2 por postgresql
#  backend:
#    image: jacobo1407b/cmu:v1.0.6-dev
#    container_name: centro-medico-backend
#    restart: on-failure
#    depends_on:
#      - postgres
#    environment:
#      - NODE_ENV=production
#      - DB_NAME=cmu
#      - DB_USER=dev
#      - DB_PASSWORD=1986
#      - DB_HOST=localhost
#      - DB_PORT=5432
#      - SECRET_TOKEN=secret
#      - ALGORITHM_JWT=HS256
#      - PORT=3001
#      - CLOUDINARY_API_KEY=862614298284656
#      - CLOUDINARY_SECRET=3Dgvj0mWYDxsksvckmbNfSzkLBs
#      - CLOUDINARY_CLOUD_NAME=dn30ekshs
#    command: ["./wait.sh", "postgres"]
#    network_mode: "host"

volumes:
  postgres_data:
    driver: local